
package se.lantmateriet.namespace.distribution.products.placename.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "placenameService", targetNamespace = "http://namespace.lantmateriet.se/distribution/products/placename/v1", wsdlLocation = "http://namespace.lantmateriet.se/distribution/products/placename/v1/placename-1.1.wsdl")
public class PlacenameService
    extends Service
{

    private final static URL PLACENAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException PLACENAMESERVICE_EXCEPTION;
    private final static QName PLACENAMESERVICE_QNAME = new QName("http://namespace.lantmateriet.se/distribution/products/placename/v1", "placenameService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://namespace.lantmateriet.se/distribution/products/placename/v1/placename-1.1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLACENAMESERVICE_WSDL_LOCATION = url;
        PLACENAMESERVICE_EXCEPTION = e;
    }

    public PlacenameService() {
        super(__getWsdlLocation(), PLACENAMESERVICE_QNAME);
    }

    public PlacenameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLACENAMESERVICE_QNAME, features);
    }

    public PlacenameService(URL wsdlLocation) {
        super(wsdlLocation, PLACENAMESERVICE_QNAME);
    }

    public PlacenameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLACENAMESERVICE_QNAME, features);
    }

    public PlacenameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlacenameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Placename
     */
    @WebEndpoint(name = "placenameSoap12")
    public Placename getPlacenameSoap12() {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/products/placename/v1", "placenameSoap12"), Placename.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Placename
     */
    @WebEndpoint(name = "placenameSoap12")
    public Placename getPlacenameSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/products/placename/v1", "placenameSoap12"), Placename.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLACENAMESERVICE_EXCEPTION!= null) {
            throw PLACENAMESERVICE_EXCEPTION;
        }
        return PLACENAMESERVICE_WSDL_LOCATION;
    }

}
