
package se.lantmateriet.namespace.distribution.produkter.byggnad.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ByggnadPortType", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    net.opengis.gml._3.ObjectFactory.class,
    se.lantmateriet.namespace.distribution.produkter.byggnad.v1.ObjectFactory.class
})
public interface ByggnadPortType {


    /**
     * 
     * @param getByggnadRequest
     * @return
     *     returns se.lantmateriet.namespace.distribution.produkter.byggnad.v1.ByggnadResponseType
     */
    @WebMethod(operationName = "GetByggnad")
    @WebResult(name = "ByggnadResponse", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", partName = "ByggnadResponse")
    public ByggnadResponseType getByggnad(
        @WebParam(name = "GetByggnadRequest", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", partName = "GetByggnadRequest")
        GetByggnadRequestType getByggnadRequest);

    /**
     * 
     * @param findByggnadRequest
     * @return
     *     returns se.lantmateriet.namespace.distribution.produkter.byggnad.v1.ByggnadsreferensResponseType
     */
    @WebMethod(operationName = "FindByggnad")
    @WebResult(name = "ByggnadsreferensResponse", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", partName = "ByggnadsreferensResponse")
    public ByggnadsreferensResponseType findByggnad(
        @WebParam(name = "FindByggnadRequest", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", partName = "FindByggnadRequest")
        FindByggnadRequestType findByggnadRequest);

}
