
package se.lantmateriet.namespace.distribution.produkter.byggnad.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ByggnadService", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", wsdlLocation = "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1/byggnad-1.3.wsdl")
public class ByggnadService
    extends Service
{

    private final static URL BYGGNADSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(se.lantmateriet.namespace.distribution.produkter.byggnad.v1.ByggnadService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = se.lantmateriet.namespace.distribution.produkter.byggnad.v1.ByggnadService.class.getResource(".");
            url = new URL(baseUrl, "http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1/byggnad-1.3.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1/byggnad-1.3.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BYGGNADSERVICE_WSDL_LOCATION = url;
    }

    public ByggnadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ByggnadService() {
        super(BYGGNADSERVICE_WSDL_LOCATION, new QName("http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", "ByggnadService"));
    }

    /**
     * 
     * @return
     *     returns ByggnadPortType
     */
    @WebEndpoint(name = "ByggnadSoapBinding")
    public ByggnadPortType getByggnadSoapBinding() {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", "ByggnadSoapBinding"), ByggnadPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ByggnadPortType
     */
    @WebEndpoint(name = "ByggnadSoapBinding")
    public ByggnadPortType getByggnadSoapBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/byggnad/v1", "ByggnadSoapBinding"), ByggnadPortType.class, features);
    }

}
