
package se.lantmateriet.namespace.distribution.produkter.uppslag.adress.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdressService", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1", wsdlLocation = "http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1/adress-1.1.wsdl")
public class AdressService
    extends Service
{

    private final static URL ADRESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADRESSSERVICE_EXCEPTION;
    private final static QName ADRESSSERVICE_QNAME = new QName("http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1", "AdressService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1/adress-1.1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADRESSSERVICE_WSDL_LOCATION = url;
        ADRESSSERVICE_EXCEPTION = e;
    }

    public AdressService() {
        super(__getWsdlLocation(), ADRESSSERVICE_QNAME);
    }

    public AdressService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADRESSSERVICE_QNAME, features);
    }

    public AdressService(URL wsdlLocation) {
        super(wsdlLocation, ADRESSSERVICE_QNAME);
    }

    public AdressService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADRESSSERVICE_QNAME, features);
    }

    public AdressService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdressService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdressPortType
     */
    @WebEndpoint(name = "AdressSoapBinding")
    public AdressPortType getAdressSoapBinding() {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1", "AdressSoapBinding"), AdressPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdressPortType
     */
    @WebEndpoint(name = "AdressSoapBinding")
    public AdressPortType getAdressSoapBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/uppslag/adress/v1", "AdressSoapBinding"), AdressPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADRESSSERVICE_EXCEPTION!= null) {
            throw ADRESSSERVICE_EXCEPTION;
        }
        return ADRESSSERVICE_WSDL_LOCATION;
    }

}
