
package se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegisterbeteckningService", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", wsdlLocation = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3/registerbeteckning-3.2.wsdl")
public class RegisterbeteckningService
    extends Service
{

    private final static URL REGISTERBETECKNINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTERBETECKNINGSERVICE_EXCEPTION;
    private final static QName REGISTERBETECKNINGSERVICE_QNAME = new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3/registerbeteckning-3.2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTERBETECKNINGSERVICE_WSDL_LOCATION = url;
        REGISTERBETECKNINGSERVICE_EXCEPTION = e;
    }

    public RegisterbeteckningService() {
        super(__getWsdlLocation(), REGISTERBETECKNINGSERVICE_QNAME);
    }

    public RegisterbeteckningService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTERBETECKNINGSERVICE_QNAME, features);
    }

    public RegisterbeteckningService(URL wsdlLocation) {
        super(wsdlLocation, REGISTERBETECKNINGSERVICE_QNAME);
    }

    public RegisterbeteckningService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTERBETECKNINGSERVICE_QNAME, features);
    }

    public RegisterbeteckningService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterbeteckningService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegisterbeteckningPortType
     */
    @WebEndpoint(name = "RegisterbeteckningSoapBinding")
    public RegisterbeteckningPortType getRegisterbeteckningSoapBinding() {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningSoapBinding"), RegisterbeteckningPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterbeteckningPortType
     */
    @WebEndpoint(name = "RegisterbeteckningSoapBinding")
    public RegisterbeteckningPortType getRegisterbeteckningSoapBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningSoapBinding"), RegisterbeteckningPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTERBETECKNINGSERVICE_EXCEPTION!= null) {
            throw REGISTERBETECKNINGSERVICE_EXCEPTION;
        }
        return REGISTERBETECKNINGSERVICE_WSDL_LOCATION;
    }

}
