
package se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RegisterbeteckningPortType", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3.ObjectFactory.class,
    net.opengis.gml._3.ObjectFactory.class
})
public interface RegisterbeteckningPortType {


    /**
     * 
     * @param getRegisterbeteckningRequest
     * @return
     *     returns se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3.RegisterbeteckningResponseType
     */
    @WebMethod(operationName = "GetRegisterbeteckning")
    @WebResult(name = "RegisterbeteckningResponse", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", partName = "RegisterbeteckningResponse")
    public RegisterbeteckningResponseType getRegisterbeteckning(
        @WebParam(name = "GetRegisterbeteckningRequest", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", partName = "GetRegisterbeteckningRequest")
        GetRegisterbeteckningRequestType getRegisterbeteckningRequest);

    /**
     * 
     * @param findRegisterbeteckningRequest
     * @return
     *     returns se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3.RegisterbeteckningsreferensResponseType
     */
    @WebMethod(operationName = "FindRegisterbeteckning")
    @WebResult(name = "RegisterbeteckningsreferensResponse", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", partName = "RegisterbeteckningsreferensResponse")
    public RegisterbeteckningsreferensResponseType findRegisterbeteckning(
        @WebParam(name = "FindRegisterbeteckningRequest", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", partName = "FindRegisterbeteckningRequest")
        FindRegisterbeteckningRequestType findRegisterbeteckningRequest);

}
