
package se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RegisterbeteckningService", targetNamespace = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", wsdlLocation = "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3/registerbeteckning-3.2.wsdl")
public class RegisterbeteckningService
    extends Service
{

    private final static URL REGISTERBETECKNINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3.RegisterbeteckningService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = se.lantmateriet.namespace.distribution.produkter.registerbeteckning.v3.RegisterbeteckningService.class.getResource(".");
            url = new URL(baseUrl, "http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3/registerbeteckning-3.2.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3/registerbeteckning-3.2.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTERBETECKNINGSERVICE_WSDL_LOCATION = url;
    }

    public RegisterbeteckningService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterbeteckningService() {
        super(REGISTERBETECKNINGSERVICE_WSDL_LOCATION, new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningService"));
    }

    /**
     * 
     * @return
     *     returns RegisterbeteckningPortType
     */
    @WebEndpoint(name = "RegisterbeteckningSoapBinding")
    public RegisterbeteckningPortType getRegisterbeteckningSoapBinding() {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningSoapBinding"), RegisterbeteckningPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterbeteckningPortType
     */
    @WebEndpoint(name = "RegisterbeteckningSoapBinding")
    public RegisterbeteckningPortType getRegisterbeteckningSoapBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://namespace.lantmateriet.se/distribution/produkter/registerbeteckning/v3", "RegisterbeteckningSoapBinding"), RegisterbeteckningPortType.class, features);
    }

}
